name: ItemShuffle
main: fr.lanfix.itemshuffle.Main
version: 1.0
author: Lanfix
api-version: 1.19
commands:
  itemshuffle:
    description: Start or stop the item shuffle, add an item to the blacklist
    permission: itemshuffle.start
    usage: /itemshuffle <start / stop / blacklistAdd / blacklistRemove>